// @ts-nocheck -- skip type checking
import * as d_docs_11 from "../content/docs/syntax.mdx?collection=docs"
import * as d_docs_10 from "../content/docs/rss.mdx?collection=docs"
import * as d_docs_9 from "../content/docs/provider.mdx?collection=docs"
import * as d_docs_8 from "../content/docs/open-in-chat.mdx?collection=docs"
import * as d_docs_7 from "../content/docs/md.mdx?collection=docs"
import * as d_docs_6 from "../content/docs/llms-txt.mdx?collection=docs"
import * as d_docs_5 from "../content/docs/index.mdx?collection=docs"
import * as d_docs_4 from "../content/docs/getting-started.mdx?collection=docs"
import * as d_docs_3 from "../content/docs/feedback.mdx?collection=docs"
import * as d_docs_2 from "../content/docs/edit-on-github.mdx?collection=docs"
import * as d_docs_1 from "../content/docs/deployment.mdx?collection=docs"
import * as d_docs_0 from "../content/docs/ask-ai.mdx?collection=docs"
import { _runtime } from "fumadocs-mdx/runtime/next"
import * as _source from "../source.config"
export const docs = _runtime.docs<typeof _source.docs>([{ info: {"path":"ask-ai.mdx","fullPath":"content/docs/ask-ai.mdx"}, data: d_docs_0 }, { info: {"path":"deployment.mdx","fullPath":"content/docs/deployment.mdx"}, data: d_docs_1 }, { info: {"path":"edit-on-github.mdx","fullPath":"content/docs/edit-on-github.mdx"}, data: d_docs_2 }, { info: {"path":"feedback.mdx","fullPath":"content/docs/feedback.mdx"}, data: d_docs_3 }, { info: {"path":"getting-started.mdx","fullPath":"content/docs/getting-started.mdx"}, data: d_docs_4 }, { info: {"path":"index.mdx","fullPath":"content/docs/index.mdx"}, data: d_docs_5 }, { info: {"path":"llms-txt.mdx","fullPath":"content/docs/llms-txt.mdx"}, data: d_docs_6 }, { info: {"path":"md.mdx","fullPath":"content/docs/md.mdx"}, data: d_docs_7 }, { info: {"path":"open-in-chat.mdx","fullPath":"content/docs/open-in-chat.mdx"}, data: d_docs_8 }, { info: {"path":"provider.mdx","fullPath":"content/docs/provider.mdx"}, data: d_docs_9 }, { info: {"path":"rss.mdx","fullPath":"content/docs/rss.mdx"}, data: d_docs_10 }, { info: {"path":"syntax.mdx","fullPath":"content/docs/syntax.mdx"}, data: d_docs_11 }], [{"info":{"path":"meta.json","fullPath":"content/docs/meta.json"},"data":{"title":"Vercel Documentation","pages":["index","getting-started","deployment","---Features---","..."],"description":"Vercel Documentation","root":true}}])