/**
 * Complete list of Tailwind CSS utility classes used by streamdown and its
 * official plugins (@streamdown/code, @streamdown/math, @streamdown/mermaid,
 * @streamdown/cjk).
 *
 * Use this list to configure Tailwind v4's `@source inline()` directive when
 * you need a custom prefix.  See the README for details.
 */
export const STREAMDOWN_CLASSES: readonly string[] = [
  "-mt-10",
  "[&>p]:inline",
  "[&_svg]:h-auto",
  "[&_svg]:w-auto",
  "[counter-increment:line_0]",
  "[counter-reset:line]",
  "[li_&]:pl-6",
  "absolute",
  "animate-spin",
  "appearance-none",
  "backdrop-blur-sm",
  "before:[counter-increment:line]",
  "before:content-[counter(line)]",
  "before:font-mono",
  "before:inline-block",
  "before:mr-4",
  "before:select-none",
  "before:text-[13px]",
  "before:text-muted-foreground/50",
  "before:text-right",
  "before:w-6",
  "bg-[var(--sdm-bg,inherit]",
  "bg-[var(--sdm-tbg)]",
  "bg-background",
  "bg-background/50",
  "bg-background/80",
  "bg-background/90",
  "bg-background/95",
  "bg-black/10",
  "bg-muted",
  "bg-muted/40",
  "bg-muted/80",
  "bg-primary",
  "bg-red-100",
  "bg-red-50",
  "bg-sidebar",
  "bg-sidebar/80",
  "block",
  "border",
  "border-b",
  "border-b-2",
  "border-border",
  "border-collapse",
  "border-current",
  "border-l-4",
  "border-muted-foreground/30",
  "border-red-200",
  "border-sidebar",
  "border-t",
  "bottom-2",
  "bottom-4",
  "break-all",
  "cursor-pointer",
  "dark:bg-[var(--shiki-dark-bg,var(--sdm-bg,inherit)]",
  "dark:bg-[var(--shiki-dark-bg,var(--sdm-tbg))]",
  "dark:text-[var(--shiki-dark,var(--sdm-c,inherit))]",
  "disabled:cursor-not-allowed",
  "disabled:opacity-50",
  "divide-border",
  "divide-y",
  "duration-150",
  "duration-200",
  "ease-out",
  "fixed",
  "flex",
  "flex-1",
  "flex-col",
  "font-medium",
  "font-mono",
  "font-semibold",
  "gap-1",
  "gap-2",
  "gap-4",
  "group",
  "group-hover:block",
  "group-hover:opacity-100",
  "h-4",
  "h-8",
  "h-[46px]",
  "h-auto",
  "h-full",
  "hidden",
  "hover:bg-background",
  "hover:bg-muted",
  "hover:bg-muted/40",
  "hover:bg-primary/90",
  "hover:text-foreground",
  "inline-block",
  "inset-0",
  "italic",
  "items-center",
  "justify-between",
  "justify-center",
  "justify-end",
  "left-2",
  "left-4",
  "list-decimal",
  "list-disc",
  "list-inside",
  "lowercase",
  "max-h-32",
  "max-w-full",
  "max-w-md",
  "mb-2",
  "min-h-28",
  "min-h-[200px]",
  "min-w-[120px]",
  "ml-1",
  "mt-1",
  "mt-2",
  "mt-6",
  "mx-4",
  "my-4",
  "my-6",
  "opacity-0",
  "origin-center",
  "overflow-hidden",
  "overflow-x-auto",
  "overflow-y-auto",
  "overscroll-y-auto",
  "p-1",
  "p-1.5",
  "p-2",
  "p-3",
  "p-4",
  "p-6",
  "pl-4",
  "pointer-events-auto",
  "pointer-events-none",
  "px-1.5",
  "px-3",
  "px-4",
  "py-0.5",
  "py-1",
  "py-2",
  "relative",
  "right-0",
  "right-2",
  "right-4",
  "rounded",
  "rounded-full",
  "rounded-lg",
  "rounded-md",
  "rounded-xl",
  "shadow-lg",
  "shadow-sm",
  "shrink-0",
  "size-4",
  "size-full",
  "space-x-2",
  "space-y-2",
  "space-y-4",
  "sticky",
  "supports-[backdrop-filter]:backdrop-blur",
  "supports-[backdrop-filter]:backdrop-blur-sm",
  "supports-[backdrop-filter]:bg-background/70",
  "supports-[backdrop-filter]:bg-sidebar/70",
  "text-2xl",
  "text-3xl",
  "text-[var(--sdm-c,inherit)]",
  "text-base",
  "text-left",
  "text-lg",
  "text-muted-foreground",
  "text-primary",
  "text-primary-foreground",
  "text-red-600",
  "text-red-700",
  "text-red-800",
  "text-sm",
  "text-xl",
  "text-xs",
  "top-2",
  "top-4",
  "top-full",
  "transition-all",
  "transition-colors",
  "transition-transform",
  "w-4",
  "w-8",
  "w-full",
  "whitespace-normal",
  "whitespace-nowrap",
  "wrap-anywhere",
  "z-10",
  "z-50",
] as const;

/**
 * Generates a Tailwind v4 `@source inline()` directive containing all
 * streamdown classes, optionally prefixed.
 *
 * @param prefix - Tailwind v4 prefix string (e.g. `"tw"` for `prefix(tw)`).
 *                 Omit or pass `undefined` when you are not using a prefix.
 * @returns       A ready-to-paste CSS `@source inline(...)` rule string.
 *
 * @example
 * // In a postcss.config.js build script, write this string to a CSS file:
 * import { getSourceInline } from 'streamdown/tailwind';
 * console.log(getSourceInline('tw'));
 * // → @source inline("tw:{absolute,animate-spin,...}");
 */
export function getSourceInline(prefix?: string): string {
  const names = [...STREAMDOWN_CLASSES];
  const body = prefix
    ? `${prefix}:{${names.join(",")}}`
    : `{${names.join(",")}}`;
  return `@source inline("${body}");`;
}
